/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_lpspi.h"
#include "fsl_lpi2c.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define LP_FLEXCOMM0_PERIPHERAL ((LPSPI_Type *)LP_FLEXCOMM0)
/* Definition of clock source frequency */
#define LP_FLEXCOMM0_CLOCK_FREQ 50000000UL
/* BOARD_InitPeripherals defines for LP_FLEXCOMM2 */
/* Definition of peripheral ID */
#define LP_FLEXCOMM2_PERIPHERAL LPI2C2
/* Definition of peripheral base address */
#define LP_FLEXCOMM2_PERIPHERAL_BASE LPI2C2_BASE
/* Definition of the clock source frequency */
#define LP_FLEXCOMM2_CLOCK_SOURCE 12000000UL

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpspi_master_config_t LP_FLEXCOMM0_config;
extern const lpi2c_master_config_t LP_FLEXCOMM2_masterConfig;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
